### ISSUE TITLE
Editing profile bugs the Save

### ISSUE THREAD

**Issue by Leftyy** [BALIST0N/Emutarkov-Alternative-Launcher#1]
Any time I change a value my game bugs out when I start it up, Giving me a error like this "The given key was not present in the dictionary"

**Comment by BALIST0N** [comment]
hi, can you send me your profile JSON please ? i will check whats wrong and whats causing the issue  : )

**Comment by Leftyy** [comment]
> 
> 
> hi, can you send me your profile JSON please ? i will check whats wrong and whats causing the issue : )

Where is it located, Im new to the whole single player tarkov so Im not sure where it would be located

**Comment by SergeyBakinskiy** [comment]
> ere is it located, Im new to the whole single player tarkov so Im not sure where it would be located

\AKI-Server\user\profiles\ххххх.json

**Comment by Leftyy** [comment]
Alrighty here you go, I got 2 so it should maybe help out more. I cant put it in here so I can send to guilded if thats cool

**Comment by BALIST0N** [comment]
fixed with commit  4c153824d89ab4b3af8d7b2d1d6bc7e0b1baaa29: )
