### ISSUE TITLE
Feature request: option to launch game but not server?

### ISSUE THREAD

**Issue by Necklaces** [BALIST0N/Emutarkov-Alternative-Launcher#2]
Wow, thanks for making this! It's awesome.

So I have this weird request. See, I'm on GNU/Linux, and this launcher actually works there (in contrast to the default launcher which doesn't even open), but unfortunately it seems like the server crashes when running through wine/proton. However, it's actually a lot easier for me to run the server on linux rather than through wine - as that is made in node - so I was wondering if you would be willing to have a checkbox or something so that linux users could launch the game but not the server?

And if you don't want to then just close this issue!

Oh and another thing, I recommend adding a license: https://choosealicense.com/ 
Of course, that's also entirely up to you. 

Cheers!

**Comment by BALIST0N** [comment]
sorry to respond this late , its because of the nature of this launcher, it open a  hidden console window in a different thread 

pretty sure wine doesn't manage this properly :( 

i can't really do something about it  sorry

**Comment by Necklaces** [comment]
All I'm asking for is a checkbox so the server command doesn't run, the rest of the program runs fine in wine.

It's your project either way. I still recommend choosing a license.
